/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as VisitRouteImport } from "./routes/visit"
import { Route as ReviewsRouteImport } from "./routes/reviews"
import { Route as ReserveRouteImport } from "./routes/reserve"
import { Route as RegisterRouteImport } from "./routes/register"
import { Route as MenuRouteImport } from "./routes/menu"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as HistoryRouteImport } from "./routes/history"
import { Route as GalleryRouteImport } from "./routes/gallery"
import { Route as EventsRouteImport } from "./routes/events"
import { Route as AboutRouteImport } from "./routes/about"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as AdminIndexRouteImport } from "./routes/admin/index"
import { Route as AdminLoginRouteImport } from "./routes/admin/login"

const VisitRoute = VisitRouteImport.update({
  id: "/visit",
  path: "/visit",
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: "/reviews",
  path: "/reviews",
  getParentRoute: () => rootRouteImport,
} as any)
const ReserveRoute = ReserveRouteImport.update({
  id: "/reserve",
  path: "/reserve",
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: "/menu",
  path: "/menu",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: "/history",
  path: "/history",
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: "/gallery",
  path: "/gallery",
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: "/events",
  path: "/events",
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: "/admin/",
  path: "/admin/",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: "/admin/login",
  path: "/admin/login",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/events": typeof EventsRoute
  "/gallery": typeof GalleryRoute
  "/history": typeof HistoryRoute
  "/login": typeof LoginRoute
  "/menu": typeof MenuRoute
  "/register": typeof RegisterRoute
  "/reserve": typeof ReserveRoute
  "/reviews": typeof ReviewsRoute
  "/visit": typeof VisitRoute
  "/admin/login": typeof AdminLoginRoute
  "/admin/": typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/events": typeof EventsRoute
  "/gallery": typeof GalleryRoute
  "/history": typeof HistoryRoute
  "/login": typeof LoginRoute
  "/menu": typeof MenuRoute
  "/register": typeof RegisterRoute
  "/reserve": typeof ReserveRoute
  "/reviews": typeof ReviewsRoute
  "/visit": typeof VisitRoute
  "/admin/login": typeof AdminLoginRoute
  "/admin": typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/events": typeof EventsRoute
  "/gallery": typeof GalleryRoute
  "/history": typeof HistoryRoute
  "/login": typeof LoginRoute
  "/menu": typeof MenuRoute
  "/register": typeof RegisterRoute
  "/reserve": typeof ReserveRoute
  "/reviews": typeof ReviewsRoute
  "/visit": typeof VisitRoute
  "/admin/login": typeof AdminLoginRoute
  "/admin/": typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/about"
    | "/events"
    | "/gallery"
    | "/history"
    | "/login"
    | "/menu"
    | "/register"
    | "/reserve"
    | "/reviews"
    | "/visit"
    | "/admin/login"
    | "/admin/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/about"
    | "/events"
    | "/gallery"
    | "/history"
    | "/login"
    | "/menu"
    | "/register"
    | "/reserve"
    | "/reviews"
    | "/visit"
    | "/admin/login"
    | "/admin"
  id:
    | "__root__"
    | "/"
    | "/about"
    | "/events"
    | "/gallery"
    | "/history"
    | "/login"
    | "/menu"
    | "/register"
    | "/reserve"
    | "/reviews"
    | "/visit"
    | "/admin/login"
    | "/admin/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EventsRoute: typeof EventsRoute
  GalleryRoute: typeof GalleryRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  MenuRoute: typeof MenuRoute
  RegisterRoute: typeof RegisterRoute
  ReserveRoute: typeof ReserveRoute
  ReviewsRoute: typeof ReviewsRoute
  VisitRoute: typeof VisitRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/visit": {
      id: "/visit"
      path: "/visit"
      fullPath: "/visit"
      preLoaderRoute: typeof VisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/reviews": {
      id: "/reviews"
      path: "/reviews"
      fullPath: "/reviews"
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/reserve": {
      id: "/reserve"
      path: "/reserve"
      fullPath: "/reserve"
      preLoaderRoute: typeof ReserveRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/register": {
      id: "/register"
      path: "/register"
      fullPath: "/register"
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/menu": {
      id: "/menu"
      path: "/menu"
      fullPath: "/menu"
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/history": {
      id: "/history"
      path: "/history"
      fullPath: "/history"
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/gallery": {
      id: "/gallery"
      path: "/gallery"
      fullPath: "/gallery"
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/events": {
      id: "/events"
      path: "/events"
      fullPath: "/events"
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/about": {
      id: "/about"
      path: "/about"
      fullPath: "/about"
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/": {
      id: "/admin/"
      path: "/admin"
      fullPath: "/admin/"
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/login": {
      id: "/admin/login"
      path: "/admin/login"
      fullPath: "/admin/login"
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EventsRoute: EventsRoute,
  GalleryRoute: GalleryRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  MenuRoute: MenuRoute,
  RegisterRoute: RegisterRoute,
  ReserveRoute: ReserveRoute,
  ReviewsRoute: ReviewsRoute,
  VisitRoute: VisitRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
